version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    container_name: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    image: rabbitmq:3.8.3-alpine
    container_name: rmq

  slave:
    build:
      context: ./slave/worker
      dockerfile: Dockerfile
    image: worker:latest
    container_name: slave
    command: sh -c "sleep 20 && python ./slave/worker/worker.py"
    volumes:
    - .:/code
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    - master
    restart: on-failure

  master:
    build:
        context: ./slave/worker
        dockerfile: Dockerfile
    image: worker:latest
    container_name: master
    command: sh -c "sleep 20 && python ./slave/worker/worker.py"
    volumes:
    - .:/code
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    restart: on-failure

  orchestrator:
    build:
        context: ./slave/orch
        dockerfile: Dockerfile
    image: orchestrator:latest
    container_name: orchestrator
    command: sh -c "sleep 15 && python ./slave/orch/orch.py"
    volumes:
        - .:/code
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    - master
    - slave
    ports:
      - "80:8001"
    restart: on-failure   

  
